#!/usr/bin/exec-suid -- /usr/bin/python3 -I
import sys
import hashlib
sys.path.append('/challenge')

def print_instructions():
    print('''
    Google "dorking" is a way of searching for information in a more advanced way. Below are some of the common keywords
    and symbols that can be used:

    OR - used to search for one thing 'or' another thing
        Example: apples OR oranges
          This will find results for apples or oranges.
    
    AND - used to search for one thing 'and' another thing
        Example: apples AND oranges
          This will find results for apples and also oranges.

    Quotes - use quotes around a search term to search for pages that explicitly have that text
        Example: "Dakota State University"
          This will find pages that have the exact text "Dakota State University".

    site:DOMAIN - used to only show results from a specific site
          Example: site:dsu.edu "academic"
            This will find the exact text "academic" on the dsu.edu website.

    There are many other things you can do with Google dorks, too much to list here.

    With the information provided here, use a Google dork to tell me the two professors at DSU that have
    the last name of "Richardson". You will need to leave pwn.college and search for this on the World Wide Web :)
    
    ''')

def print_flag():
	try:
		with open("/flag", "r") as f:
			print(f.read())
	except FileNotFoundError:
		print("Error: Flag file not found.")

def main():
    print_instructions()

    answer = input("What are the first names of the two professors at DSU with the last name 'Richardson'? (any order, space separated) ").lower()
    ans = ['760061f6bfde75c29af12f252d4d3345', '21f63c6e971cd913a9c147e8652ca659', '684c851af59965b680086b7b4896ff98']
    words = answer.strip().split(' ')
    for w in words:
        if hashlib.md5(w.encode()).hexdigest() not in ans:
            print(f'{w} is incorrect.')
            sys.exit(0)
    dork = input("\nWhat is the Google dork that you used? (copy/paste the exact search you ran): ").lower()
    ans = ['982c7190644d54ca4d902d0891d957b3', '0681a917b131a54931b64a50ce5127e0', 'c9d4f6cfc2f5c2ab97788c2a664a82d5']
    words = dork.strip().split()
    for w in words:
        if hashlib.md5(w.encode()).hexdigest() not in ans:
            print("That google dork is incorrect.")
            sys.exit(0)

    print("That is correct! An ideal dork for this search would be:")
    print("\tsite:dsu.edu \"Richardson\" AND \"Department\"")
    print("This would search dsu.edu for the name 'Richardson' and look for the text 'Department' to filter out 'Richardson Hall'")
    print("\nHere is your flag!")
    print_flag()

if __name__ == "__main__":
    main()
