FROM adbabdsu/burpimage

USER root


RUN apt update; apt install python3-flask-caching -y

RUN wget -O param_miner.bapp 'https://portswigger.net/bappstore/bapps/download/17d2949a985c4b7ca092728dba871943/34'

USER hacker