#!/usr/bin/exec-suid -- /usr/bin/python3 -I
import sys
sys.path.append('/challenge')

def print_flag(jsSecret):
	if jsSecret!=secret:
		print("No cheating!")
	else:	
		try:
			with open("/flag", "r") as f:
				text = f.read()
				# print(text)
				return text
		except FileNotFoundError:
			print("Error: Flag file not found.")

# Add your imports and other code below here
from flask import Flask, request, render_template, jsonify
import hashlib
import secrets


app = Flask(__name__)

def genSecret(length):
	return secrets.token_urlsafe(length)[:length]

@app.route('/call-python', methods=['POST'])
def call_python():
	data = request.json
	jsSecret = data.get('jsSecret')
	result = print_flag(jsSecret)
	print("RESULT HERE:", result)
	return jsonify({'flag': result})

@app.route('/get-secret', methods=['POST'])
def get_secret():
    return jsonify({'secret': secret})

@app.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@app.route('/tryUnlock', methods=['POST'])
def tryUnlock():
    agentHeader = request.headers['User-Agent']
    if (agentHeader == "flagpls"):
        return render_template('success.html', secret=secret)
    return render_template('fail.html')

@app.route('/check-pass', methods=['POST'])
def checkPass():
    message = ""
    password = request.form['pass']

    passHash = hashlib.md5(password.encode("utf-8"))
    passHash = passHash.hexdigest()

    if (passHash == "c883c31b4792bfedece68f2351e856a8"):
        message = f'WELCOME TO THE PALE RED HORSE SQUAD! Flag: {print_flag()}'
        return render_template('club.html', msg=message)
    else:
        message = 'Wrong!'
        return render_template('index.html', msg=message)
    


if __name__ == '__main__':
    secret = genSecret(16)
    app.run()